# vim: ft=yaml.docker-compose

services:
  connect-test:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    environment:
      - HOME=/data
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ENVIRONMENT=test
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - connect-data:/data

  connect-celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    depends_on:
      - connect-test
      - redis
    environment:
      - HOME=/data
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: always
    volumes:
      - connect-data:/data

  redis:
    image: redis:alpine

volumes:
  connect-data:
  redis-data:
