direction: down

classes: {
  containers: {
    shape: rectangle
  }
}

user: "User" {
  shape: person
}

database: "SQLite3" {
  shape: cylinder
}

a {
  label: null
  style.fill: transparent
  style.stroke: transparent
}

b {
  label: null
  style.fill: transparent
  style.stroke: transparent
}

b.display: "Display (Monitor or TV)" {
  style.3d: true
}

connect-nginx.class: containers
b.connect-viewer.class: containers
a.connect-server.class: containers
a.connect-websocket.class: containers
a.connect-celery.class: containers
a.redis.class: containers

user -> connect-nginx
connect-nginx <-> a.connect-server
connect-nginx -> a.connect-websocket

a.connect-server <-> a.connect-celery
a.connect-websocket <-> a.connect-server
a.connect-celery -> a.redis: "in-memory data"
a.redis <-> a.connect-server

b.connect-viewer <-> database: "assets data"

a.connect-server <-> b.connect-viewer: "assets data"
a.connect-server <-> database
a.connect-celery <-> database

b.connect-viewer -> b.display: "current asset"
