blank_issues_enabled: false
contact_links:
  - name: Screenconnect Website
    url: https://screenconnect.tccconnect.io
    about: Visit our official website for general information and documentation
  - name: Screenconnect Forum
    url: https://forums.tccconnect.io
    about: Join our community forum for help, discussions, and sharing experiences
  - name: GitHub Discussions
    url: https://github.com/Copper-Clock/Screenconnect/discussions
    about: For general questions and discussions about Screenconnect